# Pandas DataFrame Practice Exercises (Learner Version)

**Focus:** DataFrame creation, exploration, selection, cleaning, and basic data wrangling.

Write your code in the cell below each question.

## Exercise 1
Create a Pandas DataFrame using a dictionary with columns: Name, Age, City.

In [360]:
from numpy import nan
# Your code here
import pandas as pd
data = {
    'Name': [
        'Alice', 'Bob', 'Charlie', 'Diana', 'Ethan',
        'Fiona', 'George', 'Hannah', 'Ian', 'Julia','Ethan'
    ],
    'Age': [25, 30, 35, 28, 40, None , 55, 31, 27, 33, 40],
    'City': [
        'New York', 'London', nan, 'Tokyo', 'Sydney',
        'Berlin', 'Toronto', 'Madrid', 'Seoul', 'Rome', 'Sydney'
    ]
}
df = pd.DataFrame(data)
df

       Name   Age      City
0     Alice  25.0  New York
1       Bob  30.0    London
2   Charlie  35.0       NaN
3     Diana  28.0     Tokyo
4     Ethan  40.0    Sydney
5     Fiona   NaN    Berlin
6    George  55.0   Toronto
7    Hannah  31.0    Madrid
8       Ian  27.0     Seoul
9     Julia  33.0      Rome
10    Ethan  40.0    Sydney

## Exercise 2
Display the first 5 rows using `.head()`.

In [361]:
# Your code here
df.head()

      Name   Age      City
0    Alice  25.0  New York
1      Bob  30.0    London
2  Charlie  35.0       NaN
3    Diana  28.0     Tokyo
4    Ethan  40.0    Sydney

## Exercise 3
Display the last 3 rows using `.tail()`.

In [362]:
# Your code here
df.tail(3)

     Name   Age    City
8     Ian  27.0   Seoul
9   Julia  33.0    Rome
10  Ethan  40.0  Sydney

## Exercise 4
Check the shape of the DataFrame.

In [363]:
# Your code here
df.shape

(11, 3)

## Exercise 5
Use `.info()` to inspect the DataFrame.

In [364]:
# Your code here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     object
 1   Age     10 non-null     float64
 2   City    10 non-null     object
dtypes: float64(1), object(2)
memory usage: 396.0+ bytes

## Exercise 6
Generate summary statistics using `.describe()`.

In [365]:
# Your code here
df.describe()

             Age
count  10.000000
mean   34.400000
std     8.846845
min    25.000000
25%    28.500000
50%    32.000000
75%    38.750000
max    55.000000

## Exercise 7
Print DataFrame column names.

In [366]:
# Your code here
df.columns.tolist()

['Name', 'Age', 'City']

## Exercise 8
Print DataFrame index.

In [367]:
# Your code here
df.index.tolist()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Exercise 9
Check data types of each column.

In [368]:
# Your code here
df.dtypes

Name     object
Age     float64
City     object
dtype: object

## Exercise 10
Select a single column from the DataFrame.

In [369]:
# Your code here
df.Name
#df['Name']

0       Alice
1         Bob
2     Charlie
3       Diana
4       Ethan
5       Fiona
6      George
7      Hannah
8         Ian
9       Julia
10      Ethan
Name: Name, dtype: object

## Exercise 11
Select multiple columns from the DataFrame.

In [370]:
# Your code here
df[['Name','City']]

       Name      City
0     Alice  New York
1       Bob    London
2   Charlie       NaN
3     Diana     Tokyo
4     Ethan    Sydney
5     Fiona    Berlin
6    George   Toronto
7    Hannah    Madrid
8       Ian     Seoul
9     Julia      Rome
10    Ethan    Sydney

## Exercise 12
Select a specific row using `.iloc`.

In [371]:
# Your code here
df.iloc[1]

Name       Bob
Age       30.0
City    London
Name: 1, dtype: object

## Exercise 13
Select rows based on a condition (Age > 25).

In [372]:
# Your code here
df[df['Age'] > 25]

       Name   Age     City
1       Bob  30.0   London
2   Charlie  35.0      NaN
3     Diana  28.0    Tokyo
4     Ethan  40.0   Sydney
6    George  55.0  Toronto
7    Hannah  31.0   Madrid
8       Ian  27.0    Seoul
9     Julia  33.0     Rome
10    Ethan  40.0   Sydney

## Exercise 14
Sort the DataFrame by Age in descending order.

In [373]:
# Your code here
df.sort_values(by='Age',ascending=False)
print(df)

       Name   Age      City
0     Alice  25.0  New York
1       Bob  30.0    London
2   Charlie  35.0       NaN
3     Diana  28.0     Tokyo
4     Ethan  40.0    Sydney
5     Fiona   NaN    Berlin
6    George  55.0   Toronto
7    Hannah  31.0    Madrid
8       Ian  27.0     Seoul
9     Julia  33.0      Rome
10    Ethan  40.0    Sydney

## Exercise 15
Set one column as index.

In [374]:
# Your code here
df.set_index('Name',inplace=True)
df

          Age      City
Name
Alice    25.0  New York
Bob      30.0    London
Charlie  35.0       NaN
Diana    28.0     Tokyo
Ethan    40.0    Sydney
Fiona     NaN    Berlin
George   55.0   Toronto
Hannah   31.0    Madrid
Ian      27.0     Seoul
Julia    33.0      Rome
Ethan    40.0    Sydney

## Exercise 16
Reset the index back to default.

In [375]:
# Your code here
df.reset_index(inplace=True)
df

       Name   Age      City
0     Alice  25.0  New York
1       Bob  30.0    London
2   Charlie  35.0       NaN
3     Diana  28.0     Tokyo
4     Ethan  40.0    Sydney
5     Fiona   NaN    Berlin
6    George  55.0   Toronto
7    Hannah  31.0    Madrid
8       Ian  27.0     Seoul
9     Julia  33.0      Rome
10    Ethan  40.0    Sydney

## Exercise 17
Check and remove duplicate rows.

In [376]:
# Your code here
df.drop_duplicates()

      Name   Age      City
0    Alice  25.0  New York
1      Bob  30.0    London
2  Charlie  35.0       NaN
3    Diana  28.0     Tokyo
4    Ethan  40.0    Sydney
5    Fiona   NaN    Berlin
6   George  55.0   Toronto
7   Hannah  31.0    Madrid
8      Ian  27.0     Seoul
9    Julia  33.0      Rome

## Exercise 18
Rename one column in the DataFrame.

In [377]:
# Your code here
df.rename(columns={'City': 'Location'},inplace=True)
df

       Name   Age  Location
0     Alice  25.0  New York
1       Bob  30.0    London
2   Charlie  35.0       NaN
3     Diana  28.0     Tokyo
4     Ethan  40.0    Sydney
5     Fiona   NaN    Berlin
6    George  55.0   Toronto
7    Hannah  31.0    Madrid
8       Ian  27.0     Seoul
9     Julia  33.0      Rome
10    Ethan  40.0    Sydney

## Exercise 19
Add a new column to the DataFrame.

In [378]:
# Your code here
professions = [
    "Software Engineer",
    "Registered Nurse",
    "Graphic Designer",
    "Architect",
    "Financial Analyst",
    "Data Scientist",
    "Electrician",
    "Mechanical Engineer",
    "Marketing Manager",
    "Physiotherapist",
    "Professor"
]
df['Client Job'] = professions
df

       Name   Age  Location           Client Job
0     Alice  25.0  New York    Software Engineer
1       Bob  30.0    London     Registered Nurse
2   Charlie  35.0       NaN     Graphic Designer
3     Diana  28.0     Tokyo            Architect
4     Ethan  40.0    Sydney    Financial Analyst
5     Fiona   NaN    Berlin       Data Scientist
6    George  55.0   Toronto          Electrician
7    Hannah  31.0    Madrid  Mechanical Engineer
8       Ian  27.0     Seoul    Marketing Manager
9     Julia  33.0      Rome      Physiotherapist
10    Ethan  40.0    Sydney            Professor

## Exercise 20
Delete a column from the DataFrame.

In [379]:
# Your code here
del df['Age']
df

       Name  Location           Client Job
0     Alice  New York    Software Engineer
1       Bob    London     Registered Nurse
2   Charlie       NaN     Graphic Designer
3     Diana     Tokyo            Architect
4     Ethan    Sydney    Financial Analyst
5     Fiona    Berlin       Data Scientist
6    George   Toronto          Electrician
7    Hannah    Madrid  Mechanical Engineer
8       Ian     Seoul    Marketing Manager
9     Julia      Rome      Physiotherapist
10    Ethan    Sydney            Professor

## Exercise 21
Reorder the columns in a custom order.

In [380]:
# Your code here
custom = ['Name','Client Job','Location']
df = df.reindex(columns=custom)
df

       Name           Client Job  Location
0     Alice    Software Engineer  New York
1       Bob     Registered Nurse    London
2   Charlie     Graphic Designer       NaN
3     Diana            Architect     Tokyo
4     Ethan    Financial Analyst    Sydney
5     Fiona       Data Scientist    Berlin
6    George          Electrician   Toronto
7    Hannah  Mechanical Engineer    Madrid
8       Ian    Marketing Manager     Seoul
9     Julia      Physiotherapist      Rome
10    Ethan            Professor    Sydney

## Exercise 22
Clean column names (lowercase, remove spaces).

In [381]:
# Your code here
df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
df

       name           client_job  location
0     Alice    Software Engineer  New York
1       Bob     Registered Nurse    London
2   Charlie     Graphic Designer       NaN
3     Diana            Architect     Tokyo
4     Ethan    Financial Analyst    Sydney
5     Fiona       Data Scientist    Berlin
6    George          Electrician   Toronto
7    Hannah  Mechanical Engineer    Madrid
8       Ian    Marketing Manager     Seoul
9     Julia      Physiotherapist      Rome
10    Ethan            Professor    Sydney

## Exercise 23
Introduce missing values and detect them.

In [388]:
# Your code here
df.loc[0,'location'] = None
df.isna()

     name  client_job  location
0   False       False      True
1   False       False     False
2   False       False      True
3   False       False     False
4   False       False     False
5   False       False     False
6   False       False     False
7   False       False     False
8   False       False     False
9   False       False     False
10  False       False     False

## Exercise 24
Handle missing values using fillna or dropna.

In [389]:
# Your code here
df['location'].fillna('Delhi',)

0       Delhi
1      London
2       Delhi
3       Tokyo
4      Sydney
5      Berlin
6     Toronto
7      Madrid
8       Seoul
9        Rome
10     Sydney
Name: location, dtype: object